service:
  name: tennis-1point-notice

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  sendNotification:
    handler: src/handler.sendNotification
    events:
      - http:
          method: get
          path: sendNotification
  cleanUpPostedMatchData:
    handler: src/handler.cleanUpPostedMatchData